apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: local-storage #must match with the storage class name of persistant volume 
  accessModes:
    - ReadWriteOnce   # Change this if you need a different access mode
  resources:
    requests:
      storage: 10Gi   # Match this with the storage size specified in the PV