apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: sakthisaran/react-app:latest  #image of the application
        resources:
          limits:
            memory: "300Mi" #cofigure  cpu and memory based on image requirement
            cpu: "500m"
        ports:
        - containerPort: 3000 #port the application runs
