apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  type: LoadBalancer
  selector:
    app: react   # Replace this with the labels for your application
  ports:
    - protocol: TCP
      port: 8080     # The port on which the service is listening
      targetPort: 3000  # The port on which your application is running inside the pod
